### ISSUE TITLE
Add reference to Joux

### ISSUE THREAD

**Issue by emanjon** [emanjon/draft-mattsson-cfrg-aes-gcm-sst#4]

**Comment by emanjon** [comment]
```
  Joux:
    target: https://csrc.nist.gov/csrc/media/projects/block-cipher-techniques/documents/bcm/comments/800-38-series-drafts/gcm/joux_comments.pdf
    title: "Authentication Failures in NIST version of GCM"
    author:
      -
        ins: A. Joux
    date: February 2006
```
